name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # or any branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build   # Optional, if your project has a build step

      # Optional deployment step: deploying via SSH to your server
      - name: Deploy to server via SSH
        if: success()  # Only deploy if tests and build passed
        uses: appleboy/scp-action@master
        with:
          host: 54.174.67.224
          username: ubuntu
          key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAvjcB76Y1LcLmaB4ElUBQV5KlupamUfDEdy4xE9HXWYxOo9Pw
ignH3kUUF5HEvzy3hImhi3j0jxrNjvwPzo5BF3SFQXm64IpDUS36qvqEwt6dLK35
cnQzHIeG3JeWWtAj9V5f2OMBUORJjRW9eTPLA4+AIG509f3fAuVCnNcr19RF1voS
ug9iWMwEZiOqWytrLyiLeFb7wrrrsDHyhk746R+sSmzsuhbGcg2lmqASILpX8+OJ
MMJMVuClRRSmF3pHtTynJUe5pF6vtA3n6Bkfh97qbdZlUhcDL/CV5jLJ7N/y4upQ
a1mA7Ub32oHlOHalAIw8CTGdf4ADhyWVq4f+zwIDAQABAoIBAQCxQXF8cdZ8nnM3
80EyFIzKDs6B4oF7OnLa3SC+531W5XkjEg3FlPe8GYNvs1c1Hs+lotv3rO+5q7CC
3kGcqtPdl6fWLCoJtM6mh8JgMrQlJG4zhKxADCjVHTZ/uoNSfUQFE70dz+0aBKLF
5sx6ddlpqAAuOMClu75mZF5+6cThikNaUr2dV3EQhCq9E1beqHpyG/81ctsamZa1
/WTuUkvNdJF6ronguyuSEtl3FWTTtEuOgv2a530TNVZSvg78n8h08IQsnKE2idJg
D2c1AesspjNEVFQBNqTxZN1S8rD3+mMNlJkLhL7bh2on4aAfiojnaeocjpT2p0tO
ziWOZ4OBAoGBAOL2zVVWfqYz3xMxQ2+17ZYnhFaWLrlM0jlXChskcNK2qt0laOsa
9v98lBXO7PFGTPiqPwT46VIfKFm7h1F0pq2tdzB93S4SW2mZ5YfSv5m2BcRYN3oP
vuYr9Svc5IU4e5Lfdu9M5oySSqx/Un7/CHRN4S5M4MDayYW+6lyuCRoNAoGBANaM
pirYG+iTxIUWTP9ZQXuVVHTte7C7Thk7oNqemfcduwjCbNCqK1QVEhgJeXd3qhJ7
jC/a3pPkvwdt1Z+Bsy+1CdXE2xhVZ16bl5x+VyyxHPSLOhSM0AF72/bqDUNAYh2V
F1Vy1JAFHJj1DsVBXeydh6KZrBGJ1YkogHxojJFLAoGBAMtrDCm6NhTcVMks1BYh
Zmm3zUKVpBbsJVbDDgm5pW0VzxoZ12kwZ8QgcdEB/xdYPNB6NbVNKkEyL8YM74Ew
Hdt3p2XMyRnr1gZVqoULfDJWE+Egd8hsqFo/d6PyfNZyAz9mDYD42YGP9GGaU+QC
zB8BVhtbR+1RqmC29fJPAVVZAoGATciQNdhDxf5MsTN0lt71LqjlBb9TqK8/kUZc
+uWlTEIrHPHgIYaQTtuUw8Irl3R65FiGapMfPt8fosHfQQT0wccQ2b+U7y2HXHVs
cgAb+sf7h20ykWC7yM3u4YXZaRheefsjiocnKU+xHoM556nbM32pPvoXuAQQtrlI
W9JLpCECgYAvZC7zPd9BD+TZUx0DRyqhE9i0dgJj6KZR7RCJ596a6k8rRkQyw8Iw
9Jqz0R5HNLaLAzwrsoR9d7BNAMldg2KMA3REYFCTrujMkt640xgUPAlkMIZWl1wD
Or4A50xkxaww3iHIh+s72gYS8uwT7B4kW4kxZ9EuWrTVCDa+qtvRWQ==
-----END RSA PRIVATE KEY-----
          source: "dist/"      # Folder to deploy
          target: "/var/www/my-node-app"  # Target path on server
